export type {
  AnimationComplete,
  AnimationFailed,
  AnimationProgress,
  AnimationStarted,
  AudioChunk,
  BlackboardUpdate,
  ChatMessage,
  ChatRequest,
  CompleteMessage,
  ConnectionState,
  ErrorMessage,
  HintMessage,
  SocraticQuestion,
  SuggestOperation,
  TextChunk,
  UnderstandingUpdate,
  WSMessage,
} from "./types";
export { useChatWebSocket } from "./useChatWebSocket";
